repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --color always
        language: system
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
    -   id: ruff
        args: ["--fix"]
    -   id: ruff-format
    # The following can be removed once PLR0917 is out of preview
    -   name: ruff preview rules
        id: ruff
        args: ["--preview", "--select=PLR0917"]