[package]
name = "zarrs-python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "zarrs_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.0", features = ["extension-module"] }
zarrs = { version="0.15.1", features = ["http"] }
paste = "1.0"
dlpark = { version = "0.4.1", features = ["pyo3"] }
image = "0.25.0"
rayon_iter_concurrent_limit = "0.2.0"
rayon = "1.10.0"