name: zarrs-python

on:
  push:
      branches:
        - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: zarrs-python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.0"
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      
      - name: Install python deps + Build
        run: |
          uv pip install --system -e ".[test]" maturin --verbose

      - name: Test
        run: pytest     
