name: zarrs-python

on:
  push:
      branches:
        - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env: 
  CARGO_TERM_COLOR: always
  PY_COLORS: '1'

jobs:
  build_and_test:
    name: zarrs-python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install UV
        uses: hynek/setup-cached-uv@v2
        with:
          cache-dependency-path: pyproject.toml

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2
      
      - name: Install python deps + Build
        run: uv pip install --system -e ".[test]" maturin --verbose

      - name: Test python using zarr
        run: pytest zarrs_python/tests/v3
      
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
