name: zarrs-python

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: zarrs-python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install UV
        uses: hynek/setup-cached-uv@v2
        with:
          cache-dependency-path: pyproject.toml
      
      - name: Install python deps
        run: uv pip install --system -e ".[test]" maturin
      
      - name: Build
        run: maturin develop
      
      - name: Test python
        run: pytest zarrs_python/tests/v3              
